version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y                                                   
      - yum install -y git                       
      - echo Logging in to Docker Hub...
      - docker login --username andresleonleon --password '1Docker+0+0'  
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Setting up Docker Buildx...
      - docker buildx create --use               
      - docker buildx inspect --bootstrap
      - echo "Seleccionando el archivo Dockerrun.aws.json para el entorno:"
      - echo "$ENVIRONMENT" 
      - if [ "$ENVIRONMENT" == "qa" ]; then cp Dockerrun.aws.qa.json Dockerrun.aws.json; fi       
  build:
    commands:
      - echo Building the Docker image for linux/amd64...
      - docker buildx build --platform linux/amd64 --load -f Dockerfile.qa -t andresleonleon/backend-platform-qa:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push andresleonleon/backend-platform-qa:latest
      - echo Build and push completed on `date`

artifacts:
  files:
    - Dockerrun.aws.json   
  discard-paths: yes