from enum import Enum


class KEYS_ERRORS(str, Enum):
    # SPEC-001 — company_currency
    PLT_COMPANY_CURRENCY_DUPLICATE = "PLT-001"
    PLT_COMPANY_CURRENCY_BASE_ALREADY_EXISTS = "PLT-002"
    PLT_COMPANY_CURRENCY_BASE_REQUIRED = "PLT-003"
    PLT_COMPANY_CURRENCY_NOT_FOUND = "PLT-004"
    PLT_COMPANY_CURRENCY_FIRST_MUST_BE_BASE = "PLT-005"
    PLT_CURRENCY_NOT_ALLOWED_FOR_COMPANY = "PLT-006"
